- name: Send mail
  hosts: controller
  become: true
  tasks:
  - command: "cat /home/lxadmin/ansible-files/mail/bodyfile"
    register: bodyfile
  - mail:
     host: localhost
     port: 25
     from: mudaliyar.v.shankar@pwc.com
     to: mudaliyar.v.shankar@pwc.com
     subject: Test mail from Shankar
     body: "{{ bodyfile.stdout }}"
