---
- name: Create file with template
  hosts: nodes
  become: true
  vars:
    names: shankar
  tasks:
   - service:
          name: "{{ item }}"
          state: started
     with_items:
         - splunk
         - cylancesvc
         - ndtask
         - 'qualys-cloud-agent'

   - command: "/opt/splunkforwarder/bin/splunk --version"
     register: response

   - service_facts:
     register: service

   - package_facts:
           manager: auto
     register: package

   - template:
       src: jcreate.j2
       dest: /home/lxadmin/ansible-files/jinja/shankarfile.csv
     delegate_to: 10.20.246.166

- name: Sending an e-mail using the remote machine, not the Ansible controller node
  hosts: controller
  become: true
  tasks:
  -  command: "cat /home/lxadmin/ansible-files/jinja/shankarfile.csv"
     register: mailbody
     failed_when: "'FAILED' in mailbody.stderr"


  -  mail:
      host: localhost
      port: 25
      from: mudaliyar.v.shankar@pwc.com
      to:
       -  mudaliyar.v.shankar@pwc.com
      subject: Ansible-report
      body: "{{ mailbody.stdout }} {{ mailbody.stderr }}"
      attach:
      - /home/lxadmin/ansible-files/jinja/shankarfile.csv

  -  stat:
       path: /home/lxadmin/ansible-files/jinja/shankarfile.csv
     register: stat_result
  -  name: moving file
     command: mv /home/lxadmin/ansible-files/jinja/shankarfile.csv /home/lxadmin/ansible-files/jinja/shankarfile.csv.last
     when: stat_result.stat.exists == True

